#spring.datasource.url: jdbc:h2:file:./camunda-h2-database


camunda.bpm.admin-user:
  id: demo
  password: demo
camunda.bpm.filter:
  create: All tasks

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    open-in-view: false